/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class callbacks */

#ifndef _Included_callbacks
#define _Included_callbacks
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     callbacks
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_callbacks_nativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif