/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class exception */

#ifndef _Included_exception
#define _Included_exception
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     exception
 * Method:    NativeExceptionThrow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_exception_NativeExceptionThrow
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif