/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class palindrome */

#ifndef _Included_palindrome
#define _Included_palindrome
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     palindrome
 * Method:    checkpalindrome
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_palindrome_checkpalindrome
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif