/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class student */

#ifndef _Included_student
#define _Included_student
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     student
 * Method:    nativeMethod
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_student_nativeMethod
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif