/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sortarray */

#ifndef _Included_sortarray
#define _Included_sortarray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sortarray
 * Method:    displaysortarray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_sortarray_displaysortarray
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif